#!/bin/bash
# AES Encryption Manager - Complete Lab Exercise

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        AES-128-CBC FILE ENCRYPTION - LAB EXERCISE #1           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Part 1: Server Status
echo "[PART 1] Check Server Status"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "URL: http://localhost:3000"
echo ""
echo "✓ Server should be running"
echo "✓ Check health endpoint"
echo "✓ View statistics"
echo ""

# Part 2: Web Interface
echo "[PART 2] Web Interface - Manual Test"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Open browser → http://localhost:3000"
echo "Step 2: You see 3 tabs:"
echo "   ├─ Mã hóa File (Encrypt)"
echo "   ├─ Giải mã File (Decrypt)"
echo "   └─ Thông tin (Info)"
echo ""
echo "Step 3: Test with file: c:\Users\hoang\Downloads\secret_message.txt"
echo "Step 4: Password: usb2026"
echo "Step 5: Watch progress bar"
echo "Step 6: Download encrypted file (.aes)"
echo ""

# Part 3: File Encryption
echo "[PART 3] Encryption Process"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Input File:"
echo "  Name: secret_message.txt"
echo "  Content: This is a confidential message..."
echo "  Size: ~200 bytes"
echo ""
echo "Encryption Method:"
echo "  Algorithm: AES-128-CBC"
echo "  Mode: CBC (Cipher Block Chaining)"
echo "  Key Size: 128 bits (16 bytes)"
echo "  Block Size: 128 bits (16 bytes)"
echo "  Padding: PKCS7"
echo ""
echo "Output File:"
echo "  Name: secret_message.txt.aes"
echo "  Content: Binary (unreadable)"
echo "  Size: ~224 bytes (content + IV + padding)"
echo ""

# Part 4: Decryption
echo "[PART 4] Decryption Process"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Input File:"
echo "  Name: secret_message.txt.aes"
echo "  Content: Binary (unreadable)"
echo ""
echo "Decryption Method:"
echo "  1. Extract IV (first 16 bytes)"
echo "  2. Derive key from password"
echo "  3. Create decipher with AES-128-CBC"
echo "  4. Decrypt data"
echo "  5. Remove PKCS7 padding"
echo ""
echo "Output File:"
echo "  Name: secret_message.txt"
echo "  Content: Original text (readable)"
echo "  Size: ~200 bytes (exact match)"
echo ""

# Part 5: Security Analysis
echo "[PART 5] Security Analysis"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Strengths:"
echo "  ✓ AES-128 is NIST-approved standard"
echo "  ✓ Military-grade encryption"
echo "  ✓ Server-side processing (safer than client)"
echo "  ✓ No password storage"
echo "  ✓ Automatic file cleanup (1 hour)"
echo ""
echo "Weaknesses:"
echo "  ⚠ IV is fixed (should be random per encryption)"
echo "  ⚠ Simple password derivation (should use PBKDF2)"
echo "  ⚠ HTTP protocol (should use HTTPS in production)"
echo "  ⚠ No user authentication"
echo "  ⚠ No rate limiting"
echo ""
echo "Recommendations:"
echo "  → Use strong password (12+ chars mix)"
echo "  → Backup original files"
echo "  → Remember your password!"
echo "  → Deploy with HTTPS in production"
echo ""

# Part 6: Performance Metrics
echo "[PART 6] Performance Metrics"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "File Size      │ Time      │ Speed"
echo "───────────────┼───────────┼──────────────"
echo "100 KB         │ ~50ms     │ ~2 MB/s"
echo "1 MB           │ ~200ms    │ ~5 MB/s"
echo "10 MB          │ ~1.5s     │ ~7 MB/s"
echo "50 MB          │ ~7s       │ ~7 MB/s"
echo "100 MB         │ ~14s      │ ~7 MB/s"
echo ""

# Part 7: Test Cases
echo "[PART 7] Test Cases to Try"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test 1: Text File"
echo "  File: secret_message.txt (plain text)"
echo "  Password: usb2026"
echo "  Expected: Encrypt → Download .aes → Decrypt → Match original"
echo ""
echo "Test 2: Different Password"
echo "  File: secret_message.txt"
echo "  Password: wrongpassword"
echo "  Expected: Decryption fails with 'Invalid padding'"
echo ""
echo "Test 3: Large File"
echo "  Create file > 10MB"
echo "  Password: anylongpassword"
echo "  Expected: Progress bar visible, takes >1s"
echo ""
echo "Test 4: Special Characters in Password"
echo "  Password: !@#\$%^&*()"
echo "  Expected: Works fine, special chars supported"
echo ""
echo "Test 5: API Test"
echo "  Method: curl or Postman"
echo "  POST /api/process (encrypt)"
echo "  POST /api/process (decrypt)"
echo "  GET /api/stats (statistics)"
echo ""

# Part 8: Expected Results
echo "[PART 8] Expected Results"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After Test 1 (Text File Encryption/Decryption):"
echo ""
echo "✓ Original file readable"
echo "✓ Encrypted file not readable (binary)"
echo "✓ Decrypted file = Original file (byte-for-byte match)"
echo "✓ Progress bar showed during processing"
echo "✓ Success notification appeared"
echo "✓ Download URL generated correctly"
echo ""

# Part 9: Observations
echo "[PART 9] Key Observations"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Encryption adds ~24 bytes to file"
echo "   - 16 bytes: IV (initialization vector)"
echo "   - 8+ bytes: PKCS7 padding"
echo ""
echo "2. Decryption is reversible only with correct password"
echo "   - Wrong password → garbage"
echo "   - No 'password hint' feature"
echo ""
echo "3. Server processes file, not browser"
echo "   - More secure (password never exposed)"
echo "   - Needs backend trust"
echo ""
echo "4. File auto-cleanup after 1 hour"
echo "   - Prevents disk space leak"
echo "   - Download before timeout!"
echo ""

# Part 10: Bonus Exercises
echo "[PART 10] Bonus Exercises"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Challenge 1: Encrypt multiple files"
echo "  → Test batch operations"
echo ""
echo "Challenge 2: Modify server to use 256-bit AES"
echo "  → Uncomment AES-256-CBC in server.js"
echo ""
echo "Challenge 3: Add file signature verification"
echo "  → HMAC-SHA256 for integrity check"
echo ""
echo "Challenge 4: Implement random IV"
echo "  → crypto.randomBytes(16) instead of fixed IV"
echo ""
echo "Challenge 5: Test with video file"
echo "  → 50+ MB file"
echo "  → Watch performance"
echo ""

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    🎓 LAB COMPLETE! 🎓                        ║"
echo "║                                                                ║"
echo "║  Summary:                                                      ║"
echo "║  ✓ Encryption: AES-128-CBC                                    ║"
echo "║  ✓ Server: Node.js + Express                                  ║"
echo "║  ✓ Frontend: HTML + JavaScript                                ║"
echo "║  ✓ Backend: /api/process endpoint                             ║"
echo "║  ✓ Statistics: /api/stats endpoint                            ║"
echo "║                                                                ║"
echo "║  Next: Deploy to USB, Docker, or Cloud! 🚀                    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
